---
title: "CloudML Configuration"
output: 
  rmarkdown::html_vignette: default
vignette: >
  %\VignetteIndexEntry{CloudML Configuration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Configuration Files

Application deployment is configured through the use of a top-level [YAML](http://yaml.org/) file called `cloudml.yml`. To create a default configuration file run:

```{r eval=F}
library(cloudml)
cloudml_create_config()
```

Then modify this default file with the appropiate `project`, `account`, `region` and `sotage`:

```{yml}
gcloud:
  project         : "project-name"
  account         : "account@domain.com"
  region          : "us-central1"
  runtime-version : "1.2"

cloudml:
  storage         : "gs://project-name/mnist"
```

The `gcloud` key is used for configuration specific to the Google Cloud SDK, and so contains items relevant to how applications are deployed.

- Any deployments made will be associated with the `project` and `account` fields above,

- Instances provisioned for training will be launched in the region specified by `region`,

- The TensorFlow version to be used during training is configured using the `runtime-version` field.

The `storage` field in the `cloudml` section indicates where various artefacts used during provisioning and training are stored. Some useful paths to know:

- `<storage>/staging`: applications will be 'staged' in this directory; that is, your deployed application will be uploaded and built in this location;

- `<storage>/runs/<timestamp>`: training outputs will be copied to this directory.
