

## Kevin

- How exactly do I use tf learn experiment to call predict on this model. I think
  we just reconsturct the Experiment with the job/model dir and call predict on it

  NOTE: the priority is prediction with classic TF apis rather than the 
  `predict_local` function.

- More human readable job_dir names, e.g.  `20170306_1488804470` ->  `2017-03-06_@_14-24-07.234`
   
- Job status/control functions

- job_collect / job_status / etc. all need to take either a job id/name or a job object
  (otherwise you can't ever get back to them if you don't have the live job object)

- I think we should stage the contents of the application directory into a temporary directory
  before building the python package. This will eliminate the temporary writing of various 
  artifacts (which today are visible in the RStudio Files pane because train_local blocks
  the UI thread) as well as eliminate the problem of unlinking the .rds and cloudml directory.
  We have made the 'local' folder ignored by default -- if users have large datasets they
  want to use locally and not have uploaded we can document that these should go in the local 
  folder.

- Ensure python package enumerates files correctly
  https://github.com/rstudio/cloudml/commit/0c109336c366ada703ea563a1ddc806dab571cf9#commitcomment-21154573
  

## Cloud NEXT

- Sort out all of the gcloud sdk installation / authentication requirements
  for people other than us to use the package and document this well.

- Windows compatibility

- Documentation on using the package

- Pull out `hyperparameters` from config and write a new YAML file with:
    trainingInput:
       hyperparmeters:
  Then pass that to gcloud with --config hyperparmeters.yml
  
  Then in our app.R generated file where we set the config pacakge hook we 
  propagate the command line options/hyperparamters back into the config list



## Future

- install_gcloud_sdk function (see headless install in https://cloud.google.com/sdk/downloads)

- Include/exclude keys in config

- Online prediction

- Satisfying R package dependencies of train.R (packrat manifest + .Rprofile?)

- Package skeleton function w/ config.yml, train.R, etc.

- Build pane integration: Custom project type exposing various commands

- rstudioapi package making available a version of system that pumps events




